import asyncio
import logging
from app.database.db import async_session_factory
from app.services.linkedin_service import fetch_linkedin_posts
from app.core.filter_service import filter_posts
from app.core.cluster_service import cluster_posts
from app.core.ai_service import generate_ideas
from app.core.scoring_service import score_ideas
from app.pipelines.base_pipeline import store_ideas

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("test_linkedin")

async def test_pipeline():
    async with async_session_factory() as session:
        print("--- STEP 1: FETCH ---")
        posts = await fetch_linkedin_posts()
        print(f"Fetched {len(posts)} posts.")
        for i, p in enumerate(posts):
            print(f"Post {i}: engagement={p.engagement}, text[:100]={repr(p.text[:100])}")

        print("\n--- STEP 2: FILTER ---")
        filtered = filter_posts(posts)
        print(f"Filtered down to {len(filtered)} posts.")
        for i, p in enumerate(filtered):
            print(f"Filtered Post {i}: {repr(p.text[:100])}")

        if not filtered:
            print("No posts survived the filter step.")
            return

        print("\n--- STEP 3: CLUSTER ---")
        clusters = cluster_posts(filtered)
        print(f"Formed {len(clusters)} clusters.")
        for i, c in enumerate(clusters):
            print(f"Cluster {i}: size={len(c.posts)}, representative={repr(c.representative_text[:100])}")

        if not clusters:
            print("No clusters formed.")
            return

        print("\n--- STEP 4: AI GENERATE ---")
        ideas = await generate_ideas(clusters, "linkedin")
        print(f"Generated {len(ideas)} ideas.")
        for i, id_ in enumerate(ideas):
            print(f"Idea {i}: problem={repr(id_.problem[:50])}, idea={repr(id_.idea[:50])}")

        if not ideas:
            print("No ideas generated by AI.")
            return

        print("\n--- STEP 5: SCORE ---")
        scored_ideas = score_ideas(ideas)
        print(f"Scored {len(scored_ideas)} ideas.")

        print("\n--- STEP 6: STORE ---")
        stored = await store_ideas(session, scored_ideas, "linkedin")
        print(f"Stored {stored} new ideas.")

if __name__ == "__main__":
    asyncio.run(test_pipeline())
